# Generated by Django 3.1.7 on 2021-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizze', '0002_auto_20210309_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizze',
            name='immagine',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
