# Generated by Django 3.1.7 on 2021-03-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210310_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recensionemodel',
            old_name='utente',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='recensionemodel',
            name='data_pubblicazione',
        ),
    ]
