# Generated by Django 3.1.7 on 2021-03-11 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210311_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionemodel',
            name='dtata_pubblicazione',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
