# Generated by Django 3.1.7 on 2021-03-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recensionemodel_dtata_pubblicazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recensionemodel',
            options={'verbose_name': 'Recensione', 'verbose_name_plural': 'Recensioni'},
        ),
        migrations.RenameField(
            model_name='recensionemodel',
            old_name='dtata_pubblicazione',
            new_name='data_pubblicazione',
        ),
    ]
