# Generated by Django 3.1.7 on 2021-03-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizze',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizze'},
        ),
        migrations.RenameField(
            model_name='pizze',
            old_name='ingredient',
            new_name='ingredienti',
        ),
    ]
