# Generated by Django 3.1.7 on 2021-03-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizze', '0003_pizze_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizze',
            name='immagine',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=''),
        ),
    ]
